### ISSUE TITLE
Empty log windows

### ISSUE THREAD

**Issue by abrca** [WildGums/Orc.WorkspaceManagement#192]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] WPF
 - [X] .NET Standard

## Component

What component is this issue occurring in?
Orc.WorkspaceManagement.Example.NET

## Version of Library
Latest, downloaded from GitHub

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orc.WorkspaceManagement.Example.NET 
2. Do some actions, save/load workspace

## Expected Behavior
Some log messages as on https://opensource.wildgums.com/images/orc.workspacemanagement/workspace_handling.gif screenshot

## Actual Behavior
Empty log window, though file log is growing

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we'll look into this.

**Comment by GeertvanHorrik** [comment]
We've replaced the text box control with the LogViewerControl from Orc.Controls so it now updates correctly.
